name: Deploy

on:
  push:
    branches:
      - wiki

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 15
        uses: actions/setup-node@v1
        with:
          node-version: 15
      - name: Install and Build 🔧
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm install
          npm run build
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: generated
          folder: docs/.vitepress/dist
      - name: Report failure
        if: ${{ failure() }}
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.WEBHOOK_ID }}
          webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
          color: "#eb4034"
          username: "You messed up"
          message: 'Wiki deployment failed!\n\nhttps://github.com/Bedrock-OSS/bedrock-wiki/actions/runs/${{github.run_id}}'