name: Deploy

on:
  push:
    branches:
      - wiki

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 15
        uses: actions/setup-node@v1
        with:
          node-version: 15
      - name: Install and Build 🔧
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm install
          npm run build
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: generated
          folder: docs/.vitepress/dist
      - name: Bully someone into fixing it
        if: ${{ failure() }}
        uses: Bedrock-OSS/discord-bully@v1.0.3
        with:
          webhook: https://canary.discord.com/api/webhooks/${{ secrets.WEBHOOK_ID }}/${{ secrets.WEBHOOK_TOKEN }}
          emoji: <:PE_PandaBonk:885395101877166110>
          title: 'Wiki deployment failed!'