name: Deploy

on:
  push:
    branches:
      - wiki

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 15
        uses: actions/setup-node@v1
        with:
          node-version: 15
      - name: Install and Build 🔧
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm install
          npm run build
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: generated
          folder: docs/.vitepress/dist
      - name: Get bully bot
        if: ${{ failure() }}
        uses: actions/checkout@v1
        with:
          repository: 'Bedrock-OSS/discord-bully'
          path: './discord-bully'
          ref: 'master'
      - name: Bully someone into fixing it
        if: ${{ failure() }}
        env:
          WEBHOOK_ID: ${{ secrets.WEBHOOK_ID }}
          WEBHOOK_TOKEN: ${{ secrets.WEBHOOK_TOKEN }}
        working-directory: './discord-bully'
        run: |
          npm install
          npm run run